add condition to the workflows

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -39,11 +39,35 @@ jobs:
           echo
           echo 4. Which build installed?
           gradle --version
+          if [["$(ruby --version)"!= *"2.7.7"*]];
+          then
+          echo "Ruby version is not found. Installing...."
+          rbenv install 2.7.7
+          rbenv global 2.7.7
+          else
+          echo "ruby version 2.7.7 is already installed"
+          fi
           ruby --version
-          dart -v
+          if ! gem list -i "^rails$" > /dev/null 2>&1; then
+            echo "Rails not found. Installing..."
+            gem install rails
+          else
+            echo "Rails is already installed."
+          fi
+          # Verify Rails installation
+          rails --version
           flutter --version
-          rails -v
-          echo
+          if ! command -v dart >/dev/null 2>&1;
+          then
+          echo "dart not found. Installing ..."
+          mkdir -p $HOME/dart
+            curl -fsSL https://dart.dev/get/dart.zip -o dart.zip
+            unzip dart.zip -d $HOME/dart
+            export PATH="$PATH:$HOME/dart/dart-sdk/bin"
+            else
+            echo "dart is already installed"
+            fi
+            dart --version
           echo 5. Where is Android SDK Root
           echo $ANDROID_SDK_ROOT
           echo
